/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterEnterprise.WorkArea.ShelterTrainer;

import model.Model;
import model.Enterprise.CSREnterprise;
import model.Enterprise.Enterprise;
import model.Enterprise.ShelterEnterprise;
import model.Organization.Organization;
import model.Organization.ShelterUpSkillOrganization;
import model.ShelterEnterprise.ShelterUpSkillDept.ShelterTrainerProfile;
import model.csr.Opportunity;
import model.shelter.TrainingModule;
import model.userAccounts.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sritonya
 */
public class CreateTrainingModule extends javax.swing.JPanel {

    /**
     * Creates new form CreateTrainingModule
     */
    Model model;
    ShelterEnterprise enterprise;
    ShelterUpSkillOrganization organization;
    ShelterTrainerProfile currentAuthenticatedUser;
    UserAccount currentUser;
    
    Opportunity selectedOpportunity;
    
    public CreateTrainingModule(Model model, ShelterEnterprise enterprise, ShelterUpSkillOrganization organization, ShelterTrainerProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        
        this.model = model;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        
        this.selectedOpportunity = null;
        
        populateOpportunityTable();
    }
    
    public void populateOpportunityTable(){
        DefaultTableModel model = (DefaultTableModel) tblOpportunity.getModel();
        model.setRowCount(0);
        
        //find the CSR Enterprise
        CSREnterprise csrEnterprise = null;
        for(Enterprise e: model.getEnterpriseCatalog().getEnterpriseList()){
            if(e instanceof CSREnterprise){
                csrEnterprise = (CSREnterprise) e;
            }
        }
        
        for(Opportunity o : csrEnterprise.getMasterOpportunityCatalog().getOpportunityList()){
            Object[] row = new Object[4];
            row[0] = o;
            row[1] = o.getJobTitle();
            row[2] = o.getRequiredSkill().getSkillName();
            row[3] = o.getAvailablePositions();
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOpportunity = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJobDescription = new javax.swing.JTextArea();
        btnCreateTrainingModule = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Create Training Module");

        tblOpportunity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Opportunity ID", "Job Title", "Required Skill", "Available Positions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOpportunity);
        if (tblOpportunity.getColumnModel().getColumnCount() > 0) {
            tblOpportunity.getColumnModel().getColumn(0).setResizable(false);
            tblOpportunity.getColumnModel().getColumn(1).setResizable(false);
            tblOpportunity.getColumnModel().getColumn(2).setResizable(false);
            tblOpportunity.getColumnModel().getColumn(3).setResizable(false);
        }

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel4.setText("Job Description:");

        txtJobDescription.setColumns(20);
        txtJobDescription.setLineWrap(true);
        txtJobDescription.setRows(5);
        jScrollPane2.setViewportView(txtJobDescription);

        btnCreateTrainingModule.setText("CREATE MODULE");
        btnCreateTrainingModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTrainingModuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnView))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btnCreateTrainingModule))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnCreateTrainingModule)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTrainingModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTrainingModuleActionPerformed
        // TODO add your handling code here:
        
        if(selectedOpportunity == null) {
            JOptionPane.showMessageDialog(this, "Please select a Opportunity first!");
            return;
        }
            
        //Create Training Module at Shelter Training Enterprise Level and make a copy of the module for himself as well
        TrainingModule trainingModule = currentAuthenticatedUser.getShelterTrainingModule().createTrainingModule(currentAuthenticatedUser, selectedOpportunity);
        enterprise.getMasterTrainingModuleDirectory().addTrainingModule(trainingModule);
        
        this.selectedOpportunity =  null;
        txtJobDescription.setText("");
        
        JOptionPane.showMessageDialog(this, "New Training Module is successfully created");
    }//GEN-LAST:event_btnCreateTrainingModuleActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOpportunity.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from the table first to view the Job Opportunity details", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Opportunity opportunity = (Opportunity) tblOpportunity.getValueAt(selectedRow, 0);
            this.selectedOpportunity = opportunity;
            txtJobDescription.setText(opportunity.getJobDesc());
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTrainingModule;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOpportunity;
    private javax.swing.JTextArea txtJobDescription;
    // End of variables declaration//GEN-END:variables
}
