/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterEnterprise.WorkArea.ShelterTrainer;

import model.Business;
import model.Enterprise.CSREnterprise;
import model.Enterprise.Enterprise;
import model.Enterprise.ShelterEnterprise;
import model.Organization.ShelterUpSkillOrganization;
import model.Patient.PatientProfile;
import model.ShelterEnterprise.ShelterUpSkillDept.ShelterTrainerProfile;
import model.csr.Opportunity;
import model.shelter.Grade;
import model.shelter.PatientTrainer;
import model.shelter.TrainingModule;
import model.userAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sritonya
 */
public class EnrollPatients extends javax.swing.JPanel {

    /**
     * Creates new form EnrollPatients
     */
    TrainingModule selectedTrainingModule;
    PatientProfile selectedPatient;
    
    Business business;
    ShelterEnterprise enterprise;
    ShelterUpSkillOrganization organization;
    ShelterTrainerProfile currentAuthenticatedUser;
    UserAccount currentUser;
    
    public EnrollPatients(Business business, ShelterEnterprise enterprise, ShelterUpSkillOrganization organization, ShelterTrainerProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        
        this.selectedPatient = null;
        this.selectedTrainingModule = null;
        
        populateTrainingModules();
    }
    
    public void populateTrainingModules(){
        DefaultTableModel model = (DefaultTableModel) tblTrainingModules.getModel();
        model.setRowCount(0);
        
        for(TrainingModule tm : this.currentAuthenticatedUser.getShelterTrainingModule().getTrainingModuleList()){
            Object[] row = new Object[4];
            row[0] = tm;
            row[1] = tm.getOpportunity().getJobTitle();
            row[2] = tm.getOpportunity().getRequiredSkill().getSkillName();
            row[3] = tm.getEnrolledPatientList().getPatientTrainerList().size();
            model.addRow(row);
        }
    }
    
    public void populatePatients(){
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);
        
        PatientProfile patientProfile = null;
        for(UserAccount patientUser : business.getMasterPatientList().getUserAccountList()){
            patientProfile = (PatientProfile) patientUser.getAssociatedProfile();
            if(patientProfile.isIsTrainingReady() && !patientProfile.getEnrolledTrainingModules().isAlreadyEnrolled(selectedTrainingModule.getTrainingModuleId())){
                Object[] row = new Object[4];
                row[0] = patientProfile;
                row[1] = patientProfile.getPerson().getFirstName();
                row[2] = patientProfile.getPerson().getPhoneNum();
                row[3] = patientProfile.getPerson().getEmail();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrainingModules = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJobDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAssignModule = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        txtPatientName = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Enroll Patients");

        tblTrainingModules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Training Module ID", "Job Title", "Skill", "Enrolled Patients"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTrainingModules);
        if (tblTrainingModules.getColumnModel().getColumnCount() > 0) {
            tblTrainingModules.getColumnModel().getColumn(0).setResizable(false);
            tblTrainingModules.getColumnModel().getColumn(1).setResizable(false);
            tblTrainingModules.getColumnModel().getColumn(2).setResizable(false);
            tblTrainingModules.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Training Modules:");

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel4.setText("Patient Name:");

        txtJobDescription.setColumns(20);
        txtJobDescription.setLineWrap(true);
        txtJobDescription.setRows(5);
        jScrollPane2.setViewportView(txtJobDescription);

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name", "Mobile No.", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblPatients);
        if (tblPatients.getColumnModel().getColumnCount() > 0) {
            tblPatients.getColumnModel().getColumn(0).setResizable(false);
            tblPatients.getColumnModel().getColumn(1).setResizable(false);
            tblPatients.getColumnModel().getColumn(2).setResizable(false);
            tblPatients.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setText("Patients ready for training:");

        jLabel5.setText("Job Description:");

        btnAssignModule.setText("ASSIGN MODULE");
        btnAssignModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignModuleActionPerformed(evt);
            }
        });

        btnViewPatient.setText("VIEW");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewPatient)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPatientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignModule)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPatient)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnAssignModule)
                    .addComponent(txtPatientName))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTrainingModules.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from the table first to view the Training Module details", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            TrainingModule tm = (TrainingModule) tblTrainingModules.getValueAt(selectedRow, 0);
            this.selectedTrainingModule = tm;
            txtJobDescription.setText(selectedTrainingModule.getOpportunity().getJobDesc());
        }
        populatePatients();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAssignModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignModuleActionPerformed
        // TODO add your handling code here:
        if(selectedPatient != null && selectedTrainingModule != null){
            //Assign module to patient
            PatientTrainer pt = selectedPatient.getEnrolledTrainingModules().createPatientTrainer(selectedPatient, selectedTrainingModule);
            
            //Update enrolled patient list in training module object
            selectedTrainingModule.getEnrolledPatientList().addPatientTrainer(pt);
            
            this.selectedPatient = null;
            txtPatientName.setText("");
            
            populatePatients();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the training module and the patient you wish to enroll", "Warning", JOptionPane.WARNING_MESSAGE);
            return;  
        }
    }//GEN-LAST:event_btnAssignModuleActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatients.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Patient to enroll in the Training Program!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            PatientProfile patientProfile = (PatientProfile) tblPatients.getValueAt(selectedRow, 0);
            this.selectedPatient = patientProfile;
            txtPatientName.setText(selectedPatient.getPerson().getFirstName() + " " + selectedPatient.getPerson().getLastName());
        }
    }//GEN-LAST:event_btnViewPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignModule;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTable tblTrainingModules;
    private javax.swing.JTextArea txtJobDescription;
    private javax.swing.JLabel txtPatientName;
    // End of variables declaration//GEN-END:variables
}
