/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterEnterprise.WorkArea.ShelterTrainer;

import ui.ShelterEnterprise.WorkArea.ShelterTrainer.TrainerHomePage;
import model.Model;
import model.Enterprise.Enterprise;
import model.Enterprise.ShelterEnterprise;
import model.Organization.Organization;
import model.Organization.ShelterUpSkillOrganization;
import model.ShelterEnterprise.ShelterUpSkillDept.ShelterTrainerProfile;
import model.userAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sritonya
 */
public class ShelterTrainerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ShelterTrainerJPanel
     */
    JPanel UserMainContainer; 
    Model model;
    ShelterEnterprise enterprise;
    ShelterUpSkillOrganization organization;
    ShelterTrainerProfile currentAuthenticatedUser;
    UserAccount currentUser;
    public ShelterTrainerWorkArea(JPanel UserMainContainer, Model model, ShelterEnterprise enterprise, ShelterUpSkillOrganization organization, ShelterTrainerProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        
        this.UserMainContainer = UserMainContainer;
        this.model = model;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        
        goToHomePage();
    }
    
    public void goToHomePage() {
        TrainerHomePage managePatientsPanel = new TrainerHomePage(this.model, this.enterprise, this.organization, this.currentAuthenticatedUser, this.currentUser);
        shelterTrainerSplitPane.setRightComponent(managePatientsPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shelterTrainerSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnAssignPatients = new javax.swing.JButton();
        btnCreateTrainingModule = new javax.swing.JButton();
        btnEnrollPatients = new javax.swing.JButton();
        btnEnrollPatients1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        shelterTrainerSplitPane.setDividerLocation(150);

        jPanel1.setBackground(new java.awt.Color(253, 221, 221));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAssignPatients.setText("Assign Patients");
        btnAssignPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignPatientsActionPerformed(evt);
            }
        });

        btnCreateTrainingModule.setText("Create Training Module");
        btnCreateTrainingModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTrainingModuleActionPerformed(evt);
            }
        });

        btnEnrollPatients.setText("Enroll Patients");
        btnEnrollPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollPatientsActionPerformed(evt);
            }
        });

        btnEnrollPatients1.setText("Manage Training Module");
        btnEnrollPatients1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollPatients1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAssignPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCreateTrainingModule, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(btnEnrollPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEnrollPatients1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnAssignPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateTrainingModule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnrollPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnrollPatients1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        shelterTrainerSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(167, 219, 154));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Welcome Shelter Trainer!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(279, 279, 279))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitle)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        shelterTrainerSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shelterTrainerSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shelterTrainerSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        UserMainContainer.remove(this);
        CardLayout layout = (CardLayout) UserMainContainer.getLayout();
        layout.previous(UserMainContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAssignPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignPatientsActionPerformed
        // TODO add your handling code here:
        goToHomePage();
    }//GEN-LAST:event_btnAssignPatientsActionPerformed

    private void btnCreateTrainingModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTrainingModuleActionPerformed
        // TODO add your handling code here:
        CreateTrainingModule createTrainingModuleJPanel = new CreateTrainingModule(model, enterprise, organization, currentAuthenticatedUser, currentUser);
        shelterTrainerSplitPane.setRightComponent(createTrainingModuleJPanel);
    }//GEN-LAST:event_btnCreateTrainingModuleActionPerformed

    private void btnEnrollPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollPatientsActionPerformed
        // TODO add your handling code here:
        EnrollPatients enrollPatientsPanel = new EnrollPatients(model, enterprise, organization, currentAuthenticatedUser, currentUser);
        shelterTrainerSplitPane.setRightComponent(enrollPatientsPanel);
    }//GEN-LAST:event_btnEnrollPatientsActionPerformed

    private void btnEnrollPatients1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollPatients1ActionPerformed
        // TODO add your handling code here:
        ManageTrainingModules manageTrainingModulePanel = new ManageTrainingModules(model, enterprise, organization, currentAuthenticatedUser, currentUser);
        shelterTrainerSplitPane.setRightComponent(manageTrainingModulePanel);
    }//GEN-LAST:event_btnEnrollPatients1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignPatients;
    private javax.swing.JButton btnCreateTrainingModule;
    private javax.swing.JButton btnEnrollPatients;
    private javax.swing.JButton btnEnrollPatients1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane shelterTrainerSplitPane;
    // End of variables declaration//GEN-END:variables
}
