/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SignUp;

import model.Model;
import model.Enterprise.Enterprise;
import model.Organization.Organization;
import model.ShelterEnterprise.ShelterNurseStation.ShelterNurseProfile;
import model.person.Ethnicity;
import model.person.Gender;
import model.person.Person;
import model.userAccounts.UserAccount;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static utils.ModelUtils.isValidEmail;
import static utils.ModelUtils.isValidPassword;
import static utils.ModelUtils.isValidPhoneNumber;

/**
 *
 * @author sritonya
 */
public class ShelterNurseSignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShelterNurseSignUpJPanel
     */
    JPanel UserMainContainer;
    Model model;
    public ShelterNurseSignUpJPanel(JPanel UserMainContainer, Model model) {
        initComponents();
        
        this.UserMainContainer = UserMainContainer;
        this.model = model;
        
        populateDropDowns();
    }
    
    public void populateDropDowns() {
       DefaultComboBoxModel<Ethnicity> ethnicities = new DefaultComboBoxModel<>(Ethnicity.values());
       ethnicityComboBox.setModel(ethnicities);
       
       DefaultComboBoxModel<Gender> genders = new DefaultComboBoxModel<>(Gender.values());
       genderComboBox.setModel(genders);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        ethnicityComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spinnerAge = new javax.swing.JSpinner();
        txtFirstName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(167, 219, 154));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("User Name:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setText("User Credentials:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 121, -1, -1));

        genderComboBox.setToolTipText("");
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 290, 200, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 374, 200, -1));

        jLabel3.setText("Gender:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 293, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 157, 200, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 508, 100, 40));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Shelter Nurse Sign Up");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 36, -1, -1));

        jLabel6.setText("Email:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 419, -1, -1));

        jLabel4.setText("Ethnicity:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 335, -1, -1));

        labelLastName.setText("Last Name:");
        add(labelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 209, -1, -1));

        jLabel13.setText("Password:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 202, -1, -1));
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 416, 200, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Shelter Nurse's Personal Information:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 121, -1, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 206, 200, -1));

        add(ethnicityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 332, 200, -1));

        jLabel7.setText("Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 199, 200, -1));

        labelAge.setText("Age:");
        add(labelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 251, -1, -1));

        labelFirstName.setText("First Name:");
        add(labelFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 160, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 457, 200, -1));

        jLabel5.setText("Phone Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 377, -1, -1));

        spinnerAge.setModel(new javax.swing.SpinnerNumberModel(0, 0, 120, 1));
        add(spinnerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 248, 200, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 157, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:

        String patientFirstName = txtFirstName.getText();
        String patientLastName = txtLastName.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String emailId = txtEmailId.getText();
        String address = txtAddress.getText();
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        String spinnerValue = spinnerAge.getValue().toString();

        if(spinnerValue.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nurses Age is null!");
            return;
        }

        if(patientFirstName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nurses First Name can't be null!");
            return;
        }

        if(patientLastName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nurses Last Name can't be null!");
            return;
        }

        if(phoneNumber.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nurses Phone number can't be null!");
            return;
        }

        if(emailId.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nurses Email ID can't be null!");
            return;
        }

        if(address.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nurses address can't be null!");
            return;
        }

        if(userName.isBlank()){
            JOptionPane.showMessageDialog(this, "Nurses User Name can't be null!");
            return;
        }

        if(password.isBlank()){
            JOptionPane.showMessageDialog(this, "Nurses password can't be null!");
            return;
        }

        if(!isValidPassword(password)) {
            JOptionPane.showMessageDialog(this, "Nurses password is not valid!");
            return;
        }

        if(!isValidEmail(emailId)) {
            JOptionPane.showMessageDialog(this, "Nurses Email ID is invalid!");
            return;
        }

        if(!isValidPhoneNumber(phoneNumber)){
            JOptionPane.showMessageDialog(this, "Nurses Phone number is invalid!");
            return;
        }

        Gender selectedGender = (Gender) genderComboBox.getSelectedItem();

        if(selectedGender == null) {
            JOptionPane.showMessageDialog(this, "Nurses Gender is not selected!");
            return;
        }

        Ethnicity selectedEthnicity = (Ethnicity) ethnicityComboBox.getSelectedItem();

        if(selectedEthnicity == null) {
            JOptionPane.showMessageDialog(this, "Nurses Ethnicity is not selected!");
            return;
        }

        boolean isExistingUser = model.isExistingUserByUserName(userName);

        if(isExistingUser) {
            JOptionPane.showMessageDialog(this, "UserName Already exists");
            return;
        }

        //Signup Shelter Nurse
        Person p = new Person();
        p.setFirstName(patientFirstName);
        p.setLastName(patientLastName);
        p.setGender(selectedGender);
        p.setEthnicity(selectedEthnicity);
        p.setAge(Integer.parseInt(spinnerValue));
        p.setPhoneNum(phoneNumber);
        p.setEmail(emailId);
        p.setAddress(address);

        ShelterNurseProfile shelterNurse = new ShelterNurseProfile(p);

        Enterprise supportedEnterprise = model.getEnterpriseCatalog().getSupportedEnterpriseGivenRole(shelterNurse.getRole());
        Organization supportedOrganization = supportedEnterprise.getOrganizationGivenRole(shelterNurse.getRole());

        UserAccount shelterNurseUser = supportedOrganization.getOrganizationUserDirectory().createUserAccount(shelterNurse, userName, password, true);

        JOptionPane.showMessageDialog(this, "Shelter Nurse has been successfully Registered!! | " + shelterNurseUser);

        txtFirstName.setText("");
        txtLastName.setText("");
        txtPhoneNumber.setText("");
        txtEmailId.setText("");
        txtAddress.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        spinnerAge.setValue(0);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<Ethnicity> ethnicityComboBox;
    private javax.swing.JComboBox<Gender> genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JSpinner spinnerAge;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
