/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.NGOEnterprise.WorkArea.NGOAdmin;

import business.Business;
import business.Enterprise.Enterprise;
import business.Enterprise.NGOEnterprise;
import business.NGOEnterprise.NGOAdministration.NGOSupervisorProfile;
import business.NGOEnterprise.NGOVolunteer.NGOVolunteerProfile;
import business.Organization.NGOAdministrationOrganization;
import business.Organization.Organization;
import business.userAccounts.UserAccount;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Neighbourhood;

/**
 *
 * @author tbhar
 */
public class ManageNGOVolunteersJPanel extends javax.swing.JPanel {

    Business business;
    NGOEnterprise enterprise;
    NGOAdministrationOrganization organization;
    NGOSupervisorProfile currentAuthenticatedUser;
    UserAccount selectedVolunteerUser;
    UserAccount currentUser;
    /**
     * Creates new form ManageNGOVolunteersJPanel
     */
    public ManageNGOVolunteersJPanel(Business business, NGOEnterprise enterprise, NGOAdministrationOrganization organization, NGOSupervisorProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        this.selectedVolunteerUser = null;
        DisplayDateAndTime();
        populateAvailableAreas();
        populateTable();
    }
    
    public void DisplayDateAndTime() {
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        currentDate.setText("Date: " + dateFormat.format(now));
    }
    
    public void populateAvailableAreas() {
       DefaultComboBoxModel<Neighbourhood> neighbourhoods = new DefaultComboBoxModel<>(Neighbourhood.values());
       availableAreasDropDown.setModel(neighbourhoods);
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) volunteersTable.getModel();
        model.setRowCount(0);
        
        ArrayList<Organization> organizations = enterprise.getOrganizationCatalog().getOrganizationList();
        
        for(Organization org: organizations) {
           ArrayList<UserAccount> usersAccounts = org.getOrganizationUserDirectory().getUserAccountList();
           
           for(UserAccount user: usersAccounts) {
               if(user.getAssociatedProfile() instanceof NGOVolunteerProfile){
                   NGOVolunteerProfile ngoVolunteer = (NGOVolunteerProfile) user.getAssociatedProfile();
                    Object[] row = new Object[4];
                    row[0] = user;
                    row[1] = ngoVolunteer.getPerson().getEmail();
                    row[2] = ngoVolunteer.getPerson().getPhoneNum();
                    row[3] = ngoVolunteer.getAssignedNeighbourhood() != null ? ngoVolunteer.getAssignedNeighbourhood() : "-";
                    model.addRow(row);
                }
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        volunteersTable = new javax.swing.JTable();
        btnViewVolunteer = new javax.swing.JButton();
        volunteerNameLabel = new javax.swing.JLabel();
        volunteerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        enableUserDropDown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        availableAreasDropDown = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        currentDate = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(167, 219, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pageTitle.setText("View and Manage NGO Volunteers");
        jPanel1.add(pageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 10, 300, -1));

        volunteersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Email ID", "Mobile Number", "Assigned To Area"
            }
        ));
        jScrollPane1.setViewportView(volunteersTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 900, 110));

        btnViewVolunteer.setText("View");
        btnViewVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVolunteerActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 180, -1, 31));

        volunteerNameLabel.setText("Volunteer Name:");
        jPanel1.add(volunteerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 232, -1, -1));

        volunteerName.setEditable(false);
        jPanel1.add(volunteerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 229, 200, -1));

        jLabel1.setText("Assign To Area:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 314, -1, -1));

        enableUserDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel1.add(enableUserDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 270, 200, -1));

        jLabel2.setText("Enable as User:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 273, -1, -1));

        jPanel1.add(availableAreasDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 311, 200, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 361, -1, 31));

        currentDate.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        currentDate.setText("Date:");
        jPanel1.add(currentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 15, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String nameOfVolunteer = volunteerName.getText();
        
        if(nameOfVolunteer.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please select a Volunteer first!");
            return;
        }
        
        String isEnabledString = enableUserDropDown.getSelectedItem().toString();
        
        Neighbourhood selectedNeighbourhood = (Neighbourhood) availableAreasDropDown.getSelectedItem();
        
        NGOVolunteerProfile volunteer = (NGOVolunteerProfile) selectedVolunteerUser.getAssociatedProfile();
        
        this.selectedVolunteerUser.setIsUserEnabled((isEnabledString == "Yes") ? true : false);
        volunteer.setAssignedNeighbourhood(selectedNeighbourhood);
        
        
        this.selectedVolunteerUser =  null;
        
        JOptionPane.showMessageDialog(this, "Volunteer's information has been updated successfully!!!");
        populateTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnViewVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVolunteerActionPerformed
        // TODO add your handling code here:
        int selectedRow = volunteersTable.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from the table first to view the Volunteers details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            UserAccount user = (UserAccount) volunteersTable.getValueAt(selectedRow, 0);
            NGOVolunteerProfile volunteer = (NGOVolunteerProfile) user.getAssociatedProfile();
            this.selectedVolunteerUser = user;
            volunteerName.setText(volunteer.getPerson().getFirstName());
        }
    }//GEN-LAST:event_btnViewVolunteerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Neighbourhood> availableAreasDropDown;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewVolunteer;
    private javax.swing.JLabel currentDate;
    private javax.swing.JComboBox<String> enableUserDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JTextField volunteerName;
    private javax.swing.JLabel volunteerNameLabel;
    private javax.swing.JTable volunteersTable;
    // End of variables declaration//GEN-END:variables
}
