/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.NGOEnterprise.WorkArea.NGOVolunteer;

import model.Model;
import model.Enterprise.Enterprise;
import model.Enterprise.NGOEnterprise;
import model.NGOEnterprise.NGOVolunteer.NGOVolunteerProfile;
import model.Organization.NGOVolunteerOrganization;
import model.Organization.Organization;
import model.userAccounts.UserAccount;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author tbhar
 */
public class VolunteerHomePageJPanel extends javax.swing.JPanel {

    Model model;
    NGOEnterprise enterprise;
    NGOVolunteerOrganization organization;
    NGOVolunteerProfile currentAuthenticatedUser;
    UserAccount currentUser;
    /**
     * Creates new form VolunteerHomePageJPanel
     */
    public VolunteerHomePageJPanel(Model model, NGOEnterprise enterprise, NGOVolunteerOrganization organization, NGOVolunteerProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        this.model = model;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        populateData();
    }
    
    public void populateData() {
        pageLabel.setText("Welcome Volunteer, " + currentAuthenticatedUser.getPerson().getFirstName() + "!! Let's make a difference today!!");
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        currentDate.setText("Date: " + dateFormat.format(now));
        
        labelAssignedArea.setText(currentAuthenticatedUser.getAssignedNeighbourhood().getName());
        aboutTheAreaText.setText(currentAuthenticatedUser.getAssignedNeighbourhood().getDescription());
        labelNoOfPatientsSignedUp.setText(String.valueOf(currentAuthenticatedUser.getPatientOnboardedList().getPatientList().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageLabel = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        labelAssignedArea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNoOfPatientsSignedUp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutTheAreaText = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(242, 185, 197));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pageLabel.setText("Welcome Volunteer");
        add(pageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        currentDate.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        currentDate.setText("Date:");
        add(currentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 11, -1, -1));

        labelAssignedArea.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelAssignedArea.setText("jLabel3");
        add(labelAssignedArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 63, 200, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Assigned to Area:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 63, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("About the Area:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 99, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Number of Patients you have Signed up:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 213, -1, 17));

        labelNoOfPatientsSignedUp.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        labelNoOfPatientsSignedUp.setText("jLabel4");
        add(labelNoOfPatientsSignedUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 212, -1, -1));

        aboutTheAreaText.setEditable(false);
        aboutTheAreaText.setColumns(20);
        aboutTheAreaText.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        aboutTheAreaText.setLineWrap(true);
        aboutTheAreaText.setRows(5);
        jScrollPane1.setViewportView(aboutTheAreaText);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 99, 370, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutTheAreaText;
    private javax.swing.JLabel currentDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAssignedArea;
    private javax.swing.JLabel labelNoOfPatientsSignedUp;
    private javax.swing.JLabel pageLabel;
    // End of variables declaration//GEN-END:variables
}
