/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterEnterprise.WorkArea.ShelterNurse;

import model.Model;
import model.Enterprise.Enterprise;
import model.Enterprise.ShelterEnterprise;
import model.ShelterEnterprise.ShelterNurseStation.ShelterNurseProfile;
import model.Organization.Organization;
import model.Organization.ShelterNurseStationOrganization;
import model.Patient.PatientProfile;
import model.userAccounts.UserAccount;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sritonya
 */
public class NurseHomePageJPanel extends javax.swing.JPanel {

    Model model;
    ShelterEnterprise enterprise;
    ShelterNurseStationOrganization organization;
    ShelterNurseProfile currentAuthenticatedUser;
    UserAccount currentUser;
    UserAccount selectedPatient;
    /**
     * Creates new form NurseHomePageJPanel
     */
    public NurseHomePageJPanel(Model model, ShelterEnterprise enterprise, ShelterNurseStationOrganization organization, ShelterNurseProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        this.model = model;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        this.selectedPatient = null;
        populateData();
        populatePatientsTable();
    }
    
     public void populateData() {
        pageLabel.setText("Welcome Nurse, " + currentAuthenticatedUser.getPerson().getFirstName());
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        currentDate.setText("Date: " + dateFormat.format(now));
        
        labelStationArea.setText(currentAuthenticatedUser.getAssignedNurseStation().getName());
    }
     
     public void populatePatientsTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);
        
        ArrayList<UserAccount> users = model.getMasterPatientList().getUserAccountList();
        
        for(UserAccount user: users) {
            PatientProfile patient = (PatientProfile) user.getAssociatedProfile();
            if(patient.getIsCurrentlyAssignedToNurse() == null && patient.isNeedsDoctorAttention() == false){
                Object[] row = new Object[4];
                row[0] = user;
                row[1] = patient.getPerson().getFirstName();
                row[2] = patient.getPerson().getPhoneNum();
                row[3] = patient.getIsCurrentlyAssignedToDoctor() != null ? true : false;
                model.addRow(row);
            }
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageLabel = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelStationArea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(231, 231, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pageLabel.setText("Welcome Nurse");
        add(pageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        currentDate.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        currentDate.setText("Date:");
        add(currentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Assigned to Station:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, -1, -1));

        labelStationArea.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelStationArea.setText("jLabel3");
        add(labelStationArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 77, 200, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Self Assign Patients");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 113, -1, -1));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient User Name", "Patient Name", "Mobile Number", "Undergoing Doctor's Checkup?"
            }
        ));
        jScrollPane1.setViewportView(tblPatients);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 143, 888, 116));

        btnAssign.setText("Assign Patient");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 271, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatients.getSelectedRow();

        if(selectedRow < 0 ) {
            JOptionPane.showMessageDialog(this, "Please select a row to View!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        UserAccount selectedPatientUser = (UserAccount) model.getValueAt(selectedRow, 0);

        PatientProfile patient = (PatientProfile) selectedPatientUser.getAssociatedProfile();
        
        if(patient.getIsCurrentlyAssignedToNurse() != null) {
            JOptionPane.showMessageDialog(this, "Patient is currently undergoing a check-up with a doctor!");
            return;
        }
        
        patient.setIsCurrentlyAssignedToNurse(currentAuthenticatedUser);
        JOptionPane.showMessageDialog(this, "Patient has been successfully assigned to you. Please check their Vitals!");

        populatePatientsTable();
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel currentDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStationArea;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JTable tblPatients;
    // End of variables declaration//GEN-END:variables
}
