/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CSREnterprise.WorkArea.CSRAdmin;

import business.Business;
import business.CSREnterprise.CSRAdministration.CSRAdminProfile;
import business.CSREnterprise.CSREmployer.CSREmployerProfile;
import business.Enterprise.CSREnterprise;
import business.Organization.CSRAdministrationOrganization;
import business.Organization.Organization;
import business.userAccounts.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ketan
 */
public class ManageEmployerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployerJPanel
     */
    Business business;
    CSREnterprise enterprise;
    CSRAdministrationOrganization organization;
    CSRAdminProfile currentAuthenticatedUser;
    UserAccount currentUser;
    UserAccount selectedEmployerUser;
    public ManageEmployerJPanel(Business business, CSREnterprise enterprise, CSRAdministrationOrganization organization, CSRAdminProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        
        this.selectedEmployerUser = null;
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblManageEmployers.getModel();
        model.setRowCount(0);
        
        ArrayList<Organization> organizations = enterprise.getOrganizationCatalog().getOrganizationList();
        
        for(Organization org: organizations) {
           ArrayList<UserAccount> usersAccounts = org.getOrganizationUserDirectory().getUserAccountList();
           
           for(UserAccount user: usersAccounts) {
               if(user.getAssociatedProfile() instanceof CSREmployerProfile){
                   CSREmployerProfile csrEmployer = (CSREmployerProfile) user.getAssociatedProfile();
                    Object[] row = new Object[4];
                    row[0] = user;
                    row[1] = csrEmployer.getPerson().getFirstName();
                    row[2] = csrEmployer.getLicense();
                    row[3] = user.getIsUserEnabled() ? "Enabled" : "Disabled";
                    model.addRow(row);
                }
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageEmployers = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        enableUserDropDown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        volunteerNameLabel = new javax.swing.JLabel();
        txtEmployerName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(167, 219, 154));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Manage Employers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 58, 217, -1));

        tblManageEmployers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employer ID", "First Name", "Employer License", "Enabled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageEmployers);
        if (tblManageEmployers.getColumnModel().getColumnCount() > 0) {
            tblManageEmployers.getColumnModel().getColumn(0).setResizable(false);
            tblManageEmployers.getColumnModel().getColumn(1).setResizable(false);
            tblManageEmployers.getColumnModel().getColumn(2).setResizable(false);
            tblManageEmployers.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 126, 762, 110));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 122, -1));

        enableUserDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(enableUserDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 356, 200, -1));

        jLabel3.setText("Enable as User");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 359, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 391, -1, 31));

        volunteerNameLabel.setText("Employer Name");
        add(volunteerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 318, -1, -1));

        txtEmployerName.setEditable(false);
        add(txtEmployerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageEmployers.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from the table first to view the Employer details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            UserAccount user = (UserAccount) tblManageEmployers.getValueAt(selectedRow, 0);
            CSREmployerProfile employer = (CSREmployerProfile) user.getAssociatedProfile();
            this.selectedEmployerUser = user;
            txtEmployerName.setText(employer.getPerson().getFirstName());
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String nameOfEmployer = txtEmployerName.getText();
        
        if(nameOfEmployer.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please select an Employer first!");
            return;
        }
        
        String isEnabledString = enableUserDropDown.getSelectedItem().toString();
        
        
        CSREmployerProfile employer = (CSREmployerProfile) selectedEmployerUser.getAssociatedProfile();
        
        this.selectedEmployerUser.setIsUserEnabled((isEnabledString == "Yes") ? true : false);
        
        this.selectedEmployerUser =  null;
        
        JOptionPane.showMessageDialog(this, "Employer's information has been updated successfully!!!");
        populateTable();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> enableUserDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageEmployers;
    private javax.swing.JTextField txtEmployerName;
    private javax.swing.JLabel volunteerNameLabel;
    // End of variables declaration//GEN-END:variables
}
