/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.WorkAreas.PatientRole;

import model.Business;
import model.Patient.DoctorVisit;
import model.Patient.NurseVisit;
import model.Patient.PatientProfile;
import model.userAccounts.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Monisha Narendran
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    JPanel UserMainContainer;
    Business business;
    PatientProfile currentAuthenticatedUser;
    UserAccount currentUser;
    
    public PatientWorkAreaJPanel(JPanel UserMainContainer, Business business, PatientProfile currentAuthenticatedUser, UserAccount userAccount) {
        initComponents();
        
        this.UserMainContainer = UserMainContainer;
        this.business = business;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = userAccount;
        populateRecentVitals();
        populateRecentDoctorVisits();
    }
    
    public void populateRecentVitals() {
        DefaultTableModel model = (DefaultTableModel) tblVitals.getModel();
        model.setRowCount(0);
                 
         ArrayList<NurseVisit> vitals = currentAuthenticatedUser.getNurseVisits().getNurseVisitList();
         
         for(NurseVisit vital: vitals) {
             if(vital.getVital() != null) {
                Object[] row = new Object[7];
                row[0] = vital.getVital().getBloodPressure();
                row[1] = vital.getVital().getHeartRate();
                row[2] = vital.getVital().getOxygenSaturation();
                row[3] = vital.getVital().getRespiratoryRate();
                row[4] = vital.getVital().getTemperature();
                row[5] =  vital.getVital().getHeight();
                row[6] =  vital.getVital().getWeight();
                model.addRow(row);
             }
         }
    }
    
    public void populateRecentDoctorVisits() {
        DefaultTableModel model = (DefaultTableModel) lablePreviousVisits.getModel();
        model.setRowCount(0);
                 
         ArrayList<DoctorVisit> visits = currentAuthenticatedUser.getDoctorVisits().getDoctorVisitList();
         
         for(DoctorVisit visit: visits) {
             if(visit.getDoctorProfile() != null) {
                Object[] row = new Object[4];
                row[0] = visit.getDoctorProfile().getPerson().getFirstName();
                row[1] = visit.getDoctorProfile().getSpecalization();
                row[2] = visit.getPrescription();
                row[3] = visit.getNote();
                model.addRow(row);
             }
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientSplitPane = new javax.swing.JSplitPane();
        patientNavbarJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        patientWorkAreaJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVitals = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lablePreviousVisits = new javax.swing.JTable();

        patientSplitPane.setDividerLocation(120);

        patientNavbarJPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientNavbarJPanelLayout = new javax.swing.GroupLayout(patientNavbarJPanel);
        patientNavbarJPanel.setLayout(patientNavbarJPanelLayout);
        patientNavbarJPanelLayout.setHorizontalGroup(
            patientNavbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        patientNavbarJPanelLayout.setVerticalGroup(
            patientNavbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientNavbarJPanelLayout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        patientSplitPane.setLeftComponent(patientNavbarJPanel);

        patientWorkAreaJPanel.setBackground(new java.awt.Color(204, 204, 255));
        patientWorkAreaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Patient!");
        patientWorkAreaJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Previous Vitals");
        patientWorkAreaJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tblVitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Blood Pressure", "Heart Rate", "SpO2", "Respiratory Rate", "Temperature", "Height", "Weight"
            }
        ));
        jScrollPane2.setViewportView(tblVitals);

        patientWorkAreaJPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 820, 107));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Previous Doctor Visits");
        patientWorkAreaJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lablePreviousVisits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor", "Specalization", "Prescription", "Note"
            }
        ));
        jScrollPane4.setViewportView(lablePreviousVisits);

        patientWorkAreaJPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 820, 80));

        patientSplitPane.setRightComponent(patientWorkAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        UserMainContainer.remove(this);
        CardLayout layout = (CardLayout) UserMainContainer.getLayout();
        layout.previous(UserMainContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable lablePreviousVisits;
    private javax.swing.JPanel patientNavbarJPanel;
    private javax.swing.JSplitPane patientSplitPane;
    private javax.swing.JPanel patientWorkAreaJPanel;
    private javax.swing.JTable tblVitals;
    // End of variables declaration//GEN-END:variables
}
