/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterEnterprise.WorkArea.ShelterSupervisor;

import model.Business;
import model.Enterprise.Enterprise;
import model.Enterprise.ShelterEnterprise;
import model.NGOEnterprise.NGOVolunteer.NGOVolunteerProfile;
import model.ShelterEnterprise.ShelterNurseStation.ShelterNurseProfile;
import model.Organization.Organization;
import model.Organization.ShelterAdministrationOrganization;
import model.shelter.NurseStation;
import model.ShelterEnterprise.ShelterAdministration.ShelterSupervisorProfile;
import model.ShelterEnterprise.ShelterNurseStation.ShelterNurseDirectory;
import model.shelter.NurseStation;
import model.profile.UserRole;
import model.userAccounts.UserAccount;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sritonya
 */
public class ManageNursesJPanel extends javax.swing.JPanel {

    Business business;
    ShelterEnterprise enterprise;
    ShelterAdministrationOrganization organization;
    ShelterSupervisorProfile currentAuthenticatedUser;
    UserAccount selectedNurseUser;
    UserAccount currentUser;
    /**
     * Creates new form ManageNursesJPanel
     */
    public ManageNursesJPanel(Business business, ShelterEnterprise enterprise, ShelterAdministrationOrganization organization, ShelterSupervisorProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        this.selectedNurseUser = null;
        DisplayDateAndTime();
        populateNurseTable();
        populateDropDown();
    }
    
    public void DisplayDateAndTime() {
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        currentDate.setText("Date: " + dateFormat.format(now));
    }
    
    public void populateDropDown() {
       DefaultComboBoxModel<NurseStation> nurseStations = new DefaultComboBoxModel<>(NurseStation.values());
       availableStationsDropDown.setModel(nurseStations);
    }
    
    public void populateNurseTable() {
        DefaultTableModel model = (DefaultTableModel) tblNurse.getModel();
        model.setRowCount(0);

        ArrayList<UserAccount> nurseList = enterprise.getOrganizationGivenRole(UserRole.SHELTER_NURSE).getOrganizationUserDirectory().getUserAccountList();
        
        
        for(UserAccount user: nurseList) {
            ShelterNurseProfile nurseProfile = (ShelterNurseProfile) user.getAssociatedProfile();
            Object[] row = new Object[4];
            row[0] = user;
            row[1] = nurseProfile.getPerson().getEmail();
            row[2] = nurseProfile.getPerson().getPhoneNum();
            row[3] = nurseProfile.getAssignedNurseStation() != null ? nurseProfile.getAssignedNurseStation() : "-";
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNurse = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        currentDate = new javax.swing.JLabel();
        volunteerNameLabel = new javax.swing.JLabel();
        nurseName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enableUserDropDown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        availableStationsDropDown = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(132, 219, 190));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Manage Nurses");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 35, -1, -1));

        tblNurse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Email ID", "Phone Number", "Assigned Station"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNurse);
        if (tblNurse.getColumnModel().getColumnCount() > 0) {
            tblNurse.getColumnModel().getColumn(0).setResizable(false);
            tblNurse.getColumnModel().getColumn(1).setResizable(false);
            tblNurse.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 85, 723, 132));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 235, -1, -1));

        currentDate.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        currentDate.setText("Date:");
        add(currentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 40, -1, -1));

        volunteerNameLabel.setText("Nurse Name:");
        add(volunteerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 292, -1, -1));

        nurseName.setEditable(false);
        add(nurseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 289, 200, -1));

        jLabel2.setText("Enable as User:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 333, -1, -1));

        enableUserDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(enableUserDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 330, 200, -1));

        jLabel1.setText("Assign To Station:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 374, -1, -1));

        add(availableStationsDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 371, 200, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 435, -1, 31));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String nameOfNurse = nurseName.getText();
        
        if(selectedNurseUser == null) {
            JOptionPane.showMessageDialog(this, "Please select a Nurse first!");
            return;
        }

        if(nameOfNurse.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please select a Nurse first!");
            return;
        }

        String isEnabledString = enableUserDropDown.getSelectedItem().toString();

        NurseStation selectedNurseStation = (NurseStation) availableStationsDropDown.getSelectedItem();

        ShelterNurseProfile nurse = (ShelterNurseProfile) selectedNurseUser.getAssociatedProfile();

        this.selectedNurseUser.setIsUserEnabled((isEnabledString == "Yes") ? true : false);
        nurse.setAssignedNurseStation(selectedNurseStation);

        this.selectedNurseUser =  null;

        JOptionPane.showMessageDialog(this, "Nurses information has been updated successfully!!!");
        populateNurseTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNurse.getSelectedRow();
        this.selectedNurseUser = null;
        
        if(selectedRow < 0 ) {
            JOptionPane.showMessageDialog(this, "Please select a row to View!");
            return;
        } else {
                            
        DefaultTableModel model = (DefaultTableModel) tblNurse.getModel();
        UserAccount user = (UserAccount) model.getValueAt(selectedRow, 0);
        
        ShelterNurseProfile nurse = (ShelterNurseProfile) user.getAssociatedProfile();
        this.selectedNurseUser = user;
        nurseName.setText(nurse.getPerson().getFirstName());
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<NurseStation> availableStationsDropDown;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel currentDate;
    private javax.swing.JComboBox<String> enableUserDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField nurseName;
    private javax.swing.JTable tblNurse;
    private javax.swing.JLabel volunteerNameLabel;
    // End of variables declaration//GEN-END:variables
}
