/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShelterEnterprise.WorkArea.ShelterSupervisor;

import model.Business;
import model.Enterprise.ShelterEnterprise;
import model.Organization.ShelterAdministrationOrganization;
import model.ShelterEnterprise.ShelterAdministration.ShelterSupervisorProfile;
import model.ShelterEnterprise.ShelterUpSkillDept.ShelterTrainerProfile;
import model.profile.UserRole;
import model.userAccounts.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sritonya
 */
public class ManageTrainersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTrainersJPanel
     */
    Business business;
    ShelterEnterprise enterprise;
    ShelterAdministrationOrganization organization;
    ShelterSupervisorProfile currentAuthenticatedUser;
    UserAccount currentUser;
    
    UserAccount selectedTrainer;
    
    public ManageTrainersJPanel(Business business, ShelterEnterprise enterprise, ShelterAdministrationOrganization organization, ShelterSupervisorProfile currentAuthenticatedUser, UserAccount currentUser) {
        initComponents();
        
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.currentAuthenticatedUser = currentAuthenticatedUser;
        this.currentUser = currentUser;
        
        selectedTrainer = null;
        
        populateTrainersTable();
    }
    
    public void populateTrainersTable(){
        DefaultTableModel model = (DefaultTableModel) tblTrainers.getModel();
        model.setRowCount(0);

        ArrayList<UserAccount> trainerList = enterprise.getOrganizationGivenRole(UserRole.SHELTER_TRAINER).getOrganizationUserDirectory().getUserAccountList();
        
        
        for(UserAccount user: trainerList) {
            ShelterTrainerProfile trainerProfile = (ShelterTrainerProfile) user.getAssociatedProfile();
            Object[] row = new Object[6];
            row[0] = user;
            row[1] = trainerProfile.getPerson().getFirstName();
            row[2] = trainerProfile.getPerson().getLastName();
            row[3] = trainerProfile.getPerson().getAge();
            row[4] = trainerProfile.getPerson().getGender().getValue();
            row[5] = user.getIsUserEnabled() ? "Enabled" : "Disabled";
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enableUserDropDown = new javax.swing.JComboBox<>();
        lblEnabled = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrainers = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        lblNameKey = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(167, 219, 154));

        enableUserDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        enableUserDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableUserDropDownActionPerformed(evt);
            }
        });

        lblEnabled.setText("Enabled:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Manage Trainers");

        tblTrainers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trainer ID", "First Name", "Last Name", "Age", "Gender", "Enabled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTrainers);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblNameKey.setText("Name:");

        lblNameValue.setEditable(false);
        lblNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNameValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnView)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(363, 363, 363)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEnabled)
                                .addComponent(lblNameKey))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNameValue)
                                .addComponent(enableUserDropDown, 0, 150, Short.MAX_VALUE)))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameKey)
                    .addComponent(lblNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnabled)
                    .addComponent(enableUserDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enableUserDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableUserDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableUserDropDownActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTrainers.getSelectedRow();
        this.selectedTrainer = null;
        
        if(selectedRow < 0 ) {
            JOptionPane.showMessageDialog(this, "Please select a Trainer from the table");
            return;
        } else {
                            
        DefaultTableModel model = (DefaultTableModel) tblTrainers.getModel();
        UserAccount user = (UserAccount) model.getValueAt(selectedRow, 0);
        
        ShelterTrainerProfile trainer = (ShelterTrainerProfile) user.getAssociatedProfile();
        this.selectedTrainer = user;
        lblNameValue.setText(trainer.getPerson().getFirstName());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(selectedTrainer == null) {
            JOptionPane.showMessageDialog(this, "Please select a Trainer first!");
            return;
        }

        String isEnabledString = enableUserDropDown.getSelectedItem().toString();


        ShelterTrainerProfile trainer = (ShelterTrainerProfile) selectedTrainer.getAssociatedProfile();

        this.selectedTrainer.setIsUserEnabled((isEnabledString == "Yes") ? true : false);

        this.selectedTrainer =  null;

        JOptionPane.showMessageDialog(this, "Trainer information has been updated successfully!!!");
        populateTrainersTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void lblNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNameValueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> enableUserDropDown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnabled;
    private javax.swing.JLabel lblNameKey;
    private javax.swing.JTextField lblNameValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTrainers;
    // End of variables declaration//GEN-END:variables
}
